package main

import (
	"context"
	"encoding/json"
	"math/big"
	"os"
	"os/exec"
	"testing"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
)

/*
- Set up a local mainnet fork AND a local Optimism fork.
- Deploy the latest `nana-core` to both forks.
- Deploy a sucker to project #1.
- Claim from several wallets, using the proofs generated by `juicerkle`.
*/

func TestE2E(t *testing.T) {
	// Read test config from 'test_config.json'
	var testConfig struct {
		MainnetRPC  string `json:"mainnetRPC"`
		OptimismRPC string `json:"optimismRPC"`
	}
	testConfigFile, err := os.ReadFile("test_config.json")
	if err != nil {
		t.Fatalf("Failed to open 'test_config.json': %v", err)
	}
	if err := json.Unmarshal(testConfigFile, &testConfig); err != nil {
		t.Fatalf("Failed to decode 'test_config.json': %v", err)
	}

	// Make sure the necessary tools are installed
	tools := []string{"git", "forge", "anvil", "npm"}
	for _, tool := range tools {
		if _, err := exec.LookPath(tool); err != nil {
			t.Fatalf("Could not find '%s' executable in path: %v", tool, err)
		}
	}

	// Set up mainnet fork
	mainnetChainId := big.NewInt(1)
	mainnetPort := "8545"
	mainnetCmd := exec.Command("anvil", "--fork-url", testConfig.MainnetRPC, "--chain-id", mainnetChainId.String(),
		"--port", mainnetPort, "--silent", "--auto-impersonate")
	if err := mainnetCmd.Start(); err != nil {
		t.Fatalf("Failed to launch mainnet fork: %v", err)
	}
	defer mainnetCmd.Process.Kill()

	// Set up op fork
	opChainId := big.NewInt(10)
	opPort := "8546"
	opCmd := exec.Command("anvil", "--fork-url", testConfig.OptimismRPC, "--chain-id", opChainId.String(),
		"--port", opPort, "--silent", "--auto-impersonate", "--optimism")
	if err := opCmd.Start(); err != nil {
		t.Fatalf("Failed to launch op fork: %v", err)
	}
	defer opCmd.Process.Kill()

	// Dial the forks
	deadline := time.Now().Add(time.Second * 10)
	var mainnetClient, opClient *ethclient.Client
	var mainnetErr, opErr error
	for time.Now().Before(deadline) { // Retry until the deadline
		time.Sleep(time.Second)
		mainnetClient, mainnetErr = ethclient.Dial("http://localhost:" + mainnetPort)
		opClient, opErr = ethclient.Dial("http://localhost:" + opPort)
	}

	if mainnetErr != nil {
		t.Fatalf("Failed to dial mainnet fork: %v", mainnetErr)
	}
	if opErr != nil {
		t.Fatalf("Failed to dial op fork: %v", opErr)
	}
	defer mainnetClient.Close()
	defer opClient.Close()

	// Testing accounts
	account1 := common.HexToAddress("0x1")
	balanceBefore, err := mainnetClient.BalanceAt(context.Background(), account1, nil)
	if err != nil {
		t.Fatalf("Failed to get balance of account1: %v", err)
	}

	var result bool
	err = mainnetClient.Client().Call(&result, "anvil_setBalance", account1, "0x3635c9adc5dea00000")
	if err != nil {
		t.Fatalf("Failed to set balance: %v", err)
	}

	balanceAfter, err := mainnetClient.BalanceAt(context.Background(), account1, nil)
	if err != nil {
		t.Fatalf("Failed to get balance of account1: %v", err)
	}

	t.Logf("Balance before: %v", balanceBefore)
	t.Logf("Balance after: %v", balanceAfter)
	t.Error("")

	// Create a temporary folder for testing
	tempDir, err := os.MkdirTemp("", "juicerkle-test")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	t.Logf("Temp dir: %s", tempDir)
	defer os.RemoveAll(tempDir)

	repos := []struct {
		url           string
		name          string
		deployCommand string
		deployArgs    []string
	}{
		{
			url:           "https://github.com/Bananapus/nana-core.git",
			name:          "nana-core",
			deployCommand: "forge",
			deployArgs:    []string{}, // TODO: Add args
		},
		{
			url:           "https://github.com/Bananapus/nana-suckers.git",
			name:          "nana-suckers",
			deployCommand: "forge",
			deployArgs:    []string{}, // TODO: Add args
		},
	}
	for _, repo := range repos {
		// Clone
		cmd := exec.Command("git", "clone", repo.url, tempDir+"/"+repo.name)
		if err := cmd.Run(); err != nil {
			t.Fatalf("Failed to clone repo '%s': %v", repo.url, err)
		}
		if err := os.Chdir(tempDir + "/" + repo.name); err != nil {
			t.Fatalf("Failed to change to directory '%s': %v", tempDir+"/"+repo.name, err)
		}

		// Install npm dependencies
		cmd = exec.Command("npm", "ci")
		if err := cmd.Run(); err != nil {
			t.Fatalf("Failed to run 'npm ci' in '%s': %v", repo.name, err)
		}

		// Deploy
		cmd = exec.Command(repo.deployCommand, repo.deployArgs...)
		if err := cmd.Run(); err != nil {
			t.Fatalf("Failed to run '%s' with args '%s' in '%s': %v", repo.deployCommand, repo.deployArgs, repo.name, err)
		}
	}

	// Set up testing database
	originalTreeDb := treeDb
	treeDb = "testTrees.db"
	defer func() { treeDb = originalTreeDb }() // reset to default after the test
	if err := initDb(); err != nil {
		t.Fatalf("Failed to initialize database: %v", err)
	}
	defer db.Close()
}
